version: '3'
services:
  webserver:
    build:
      context: ./containers/nginx
    volumes:
      - ./containers/nginx/conf.d/default-local.conf:/etc/nginx/conf.d/default.conf
      - ./spa:/var/www/spa
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api
      - spa
    restart: "no"

  api:
    build:
      context: ./containers/php
    environment:
      - APP_ENV=${APP_ENV:-local}
      - DOCUMENT_ROOT=/var/www/html/public
    volumes:
      - ../api:/var/www/html
    working_dir: /var/www/html
    expose:
      - 80
    depends_on:
      - db
